### ISSUE TITLE
Providing setupFile causes run failure

### ISSUE THREAD

**Issue by soumyamahunt** [mrchief/universal-changelog-action#34]
If `setupFile` is provided in config, action is failing with error `Error: join is not defined`, on looking into [changelog.js](https://github.com/mrchief/universal-changelog-action/blob/337544f3b3c44e48da2ffd8810290afaa7a20008/lib/changelog.js#L57) it is missing import for `join` function.

**Comment by mrchief** [comment]
`join` is a [native function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) so there's nothing to import. I think the problem lies elsewhere.

**Comment by soumyamahunt** [comment]
> native function

I think the `join` function you have shared is for array, but the function in code is for path.

**Comment by mrchief** [comment]
> I think the join function you have shared is for array

That's because the line you referred to in your original comment is producing a JS array. 😄 

I see that you updated your comment and yes, it requires a import for the one you pointed out in your latest.

**Comment by soumyamahunt** [comment]
> > I think the join function you have shared is for array
> 
> That's because the line you referred to in your original comment is producing a JS array. 😄
> 
> I see that you updated your comment and yes, it requires a import for the one you pointed out in your latest.

Yeah the original issue didn't contain link to the exact line (instead it pointed to just the file), I guess that was causing confusion 😄.
